-- Add per-resource cost columns to service cost report tables.
ALTER TABLE service_cost_reports
    ADD COLUMN IF NOT EXISTS cpu_cost BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ram_cost BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ssd_cost BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hdd_cost BIGINT NOT NULL DEFAULT 0;

ALTER TABLE service_cost_reports_by_dc
    ADD COLUMN IF NOT EXISTS cpu_cost BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ram_cost BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ssd_cost BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hdd_cost BIGINT NOT NULL DEFAULT 0;